"""Catalog of factors and data modules used in the NIFTY 50 hybrid prediction pipeline."""

from __future__ import annotations

from typing import Any

NIFTY_FACTOR_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "key": "oil_brent",
        "label": "Brent crude",
        "category": "macro_global",
        "source": "yfinance",
        "role": "Macro Ridge input — energy import cost proxy for India",
    },
    {
        "key": "oil_wti",
        "label": "WTI crude",
        "category": "macro_global",
        "source": "yfinance",
        "role": "Macro Ridge input — global oil benchmark",
    },
    {
        "key": "usd_inr",
        "label": "USD/INR",
        "category": "macro_global",
        "source": "yfinance + datasets/exchange-rates (GitHub)",
        "role": "Macro Ridge input — FX pressure on imports and FII flows",
    },
    {
        "key": "gold",
        "label": "Gold",
        "category": "macro_global",
        "source": "yfinance + datasets/gold-prices (GitHub)",
        "role": "Macro Ridge input — safe-haven / inflation proxy",
    },
    {
        "key": "sp500",
        "label": "S&P 500",
        "category": "macro_global",
        "source": "yfinance",
        "role": "Macro Ridge input — global risk appetite",
    },
    {
        "key": "us_10y",
        "label": "US 10Y yield",
        "category": "macro_global",
        "source": "FRED / datasets/bond-yields-us-10y (GitHub)",
        "role": "Macro Ridge input — global rates and EM flow pressure",
    },
    {
        "key": "us_10y_velocity_3d",
        "label": "US 10Y yield velocity (3d)",
        "category": "macro_global",
        "source": "Derived from us_10y (spread_features)",
        "role": "Macro Ridge input — rate-of-change in US yields",
    },
    {
        "key": "vix",
        "label": "CBOE VIX",
        "category": "macro_global",
        "source": "datasets/finance-vix (GitHub)",
        "role": "Global fear gauge — risk-off proxy (distinct from india_vix)",
    },
    {
        "key": "india_vix",
        "label": "India VIX",
        "category": "macro_global",
        "source": "OpenAlgo INDstocks · nselib · yfinance",
        "role": "Macro Ridge + regime — implied volatility on NIFTY",
    },
    {
        "key": "fii_net_5d",
        "label": "FII net (5d)",
        "category": "macro_global",
        "source": "NSE / nse_browser · MrChartist/fii-dii-data · niftyinvest",
        "role": "Macro Ridge input — foreign institutional flow momentum",
    },
    {
        "key": "dii_net_5d",
        "label": "DII net (5d)",
        "category": "macro_global",
        "source": "NSE / nse_browser · MrChartist/fii-dii-data · niftyinvest",
        "role": "Macro Ridge input — domestic institutional flow (often offsets FII)",
    },
    {
        "key": "institutional_net_5d",
        "label": "Institutional net (5d)",
        "category": "macro_global",
        "source": "FII + DII rolling sum / backfill",
        "role": "Macro Ridge input — combined FII+DII 5-session flow",
    },
    {
        "key": "dii_absorption_ratio",
        "label": "DII absorption ratio",
        "category": "macro_global",
        "source": "FII vs DII rolling / backfill",
        "role": "Macro Ridge input — domestic offset vs foreign selling",
    },
    {
        "key": "fpi_equity_net_usd",
        "label": "FPI equity net (USD)",
        "category": "macro_global",
        "source": "NSDL / nse_browser",
        "role": "Macro Ridge input — confirmed foreign equity flow from NSDL custodian data",
    },
    {
        "key": "fpi_debt_net_usd",
        "label": "FPI debt net (USD)",
        "category": "macro_global",
        "source": "NSDL / nse_browser",
        "role": "Macro Ridge input — foreign debt flow; complements equity FII provisional NSE data",
    },
    {
        "key": "fii_fut_long_short_ratio",
        "label": "FII index fut long/short",
        "category": "derivatives",
        "source": "NSE FII positioning / backfill",
        "role": "Macro Ridge input — FII index futures positioning",
    },
    {
        "key": "nifty_pe",
        "label": "NIFTY trailing P/E",
        "category": "macro_global",
        "source": "data/nse/historic_data PE/PB CSV · RSwarnkar GitHub · Kaggle obiwankanobi · OpenAlgo · SearXNG",
        "role": "Macro Ridge input — valuation stretch",
    },
    {
        "key": "nifty_earnings_yield",
        "label": "NIFTY earnings yield (E/P)",
        "category": "valuation",
        "source": "Derived from nifty_pe",
        "role": "Phase I — structural floor; E/P vs bond yield gap",
    },
    {
        "key": "nifty_dividend_yield",
        "label": "NIFTY dividend yield (D/P)",
        "category": "valuation",
        "source": "NSE index factsheet / nifty50_valuation_daily cold tier",
        "role": "Phase I — income floor; spikes signal buy regime",
    },
    {
        "key": "nifty_pb",
        "label": "NIFTY price-to-book",
        "category": "valuation",
        "source": "NSE PE/PB CSV / nifty50_valuation_daily cold tier",
        "role": "Phase I — raw valuation level for Ridge",
    },
    {
        "key": "nifty_book_to_market",
        "label": "NIFTY book-to-market (B/M)",
        "category": "valuation",
        "source": "Derived: 1 / nifty_pb",
        "role": "Phase I — value factor literature parity",
    },
    {
        "key": "nifty_pb_zscore_5y",
        "label": "NIFTY P/B z-score (5y)",
        "category": "valuation",
        "source": "Derived from nifty_pb rolling 5y window",
        "role": "Phase I — extreme P/B vs history → reversal signal",
    },
    {
        "key": "equity_risk_premium",
        "label": "Equity risk premium",
        "category": "valuation",
        "source": "Derived: E/P − India 10Y (or repo proxy)",
        "role": "Phase I — equity vs debt attractiveness",
    },
    {
        "key": "india_term_spread",
        "label": "India term spread",
        "category": "liquidity_spread",
        "source": "Derived: india_10y − india_91d_tbill",
        "role": "Phase I — yield curve expansion signal",
    },
    {
        "key": "india_10y",
        "label": "India 10Y G-Sec yield",
        "category": "liquidity_spread",
        "source": "RBI WSS cold tier / FRED / repo+spread proxy",
        "role": "Phase I — cost of capital for ERP and term spread",
    },
    {
        "key": "india_91d_tbill",
        "label": "India 91-day T-Bill yield",
        "category": "liquidity_spread",
        "source": "RBI WSS cold tier / repo proxy",
        "role": "Phase I — short-rate anchor for term spread",
    },
    {
        "key": "india_credit_spread",
        "label": "India corporate credit spread",
        "category": "liquidity_spread",
        "source": "Env override or term-spread proxy (CRISIL CSV pending)",
        "role": "Phase I — credit stress leading indicator for equities",
    },
    {
        "key": "india_vix_velocity_3d",
        "label": "India VIX velocity (3d)",
        "category": "volatility",
        "source": "Derived from india_vix history",
        "role": "Phase I — fear acceleration (14d negative predictor)",
    },
    {
        "key": "usd_inr_momentum_5d",
        "label": "USD/INR momentum (5d)",
        "category": "macro_global",
        "source": "Derived from usd_inr history",
        "role": "Phase I — INR depreciation headwind for FII returns",
    },
    {
        "key": "fii_net_5d_momentum",
        "label": "FII net 5d momentum",
        "category": "macro_global",
        "source": "Derived from fii_net_5d",
        "role": "Phase I — flow acceleration",
    },
    {
        "key": "cpi_yoy_proxy",
        "label": "CPI YoY proxy",
        "category": "macro_global",
        "source": "RBI / ETF proxy",
        "role": "Macro Ridge input — inflation regime",
    },
    {
        "key": "repo_rate",
        "label": "RBI repo rate",
        "category": "macro_global",
        "source": "RBI context",
        "role": "Macro Ridge + scenarios — policy rate",
    },
    {
        "key": "index_sentiment",
        "label": "Index sentiment",
        "category": "constituent_aggregate",
        "source": "FinBERT batch mean",
        "role": "Macro Ridge input — mean constituent news sentiment",
    },
    {
        "key": "nifty_pcr",
        "label": "NIFTY put/call ratio",
        "category": "derivatives",
        "source": "OpenAlgo option chain",
        "role": "Macro Ridge input — options positioning / fear gauge",
    },
    {
        "key": "qfinindia_expected_move",
        "label": "Expected move (ATM vol)",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Macro Ridge input — implied move from chain analytics",
    },
    {
        "key": "qfinindia_skew",
        "label": "Volatility skew",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Macro Ridge input — put/call skew from chain analytics",
    },
    {
        "key": "qfinindia_tail_risk",
        "label": "Tail risk metric",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Macro Ridge input — OTM wing risk from chain analytics",
    },
    {
        "key": "nifty_return_7d",
        "label": "NIFTY 7d return",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — short-term price momentum",
    },
    {
        "key": "nifty_return_14d",
        "label": "NIFTY 14d return",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — medium-term momentum",
    },
    {
        "key": "nifty_rsi_14",
        "label": "NIFTY RSI(14)",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — overbought/oversold",
    },
    {
        "key": "nifty_realized_vol_20d",
        "label": "NIFTY realized vol (20d)",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — recent realized volatility",
    },
    {
        "key": "nifty_ma20_distance_pct",
        "label": "Distance from 20d MA",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — mean-reversion stretch",
    },
    {
        "key": "nifty_ma50_distance_pct",
        "label": "Distance from 50d MA",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — medium-term trend stretch",
    },
    {
        "key": "nifty_ma200_distance_pct",
        "label": "Distance from 200d MA",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — structural trend stretch",
    },
    {
        "key": "nifty_macd_line",
        "label": "NIFTY MACD line",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — MACD momentum",
    },
    {
        "key": "nifty_macd_signal",
        "label": "NIFTY MACD signal",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — MACD signal line",
    },
    {
        "key": "nifty_macd_histogram",
        "label": "NIFTY MACD histogram",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — MACD histogram momentum",
    },
    {
        "key": "nifty_bb_percent_b",
        "label": "NIFTY Bollinger %B",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — band position / stretch",
    },
    {
        "key": "nifty_bb_width_pct",
        "label": "NIFTY Bollinger width",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — volatility compression/expansion",
    },
    {
        "key": "nifty_stoch_k",
        "label": "NIFTY Stochastic %K",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — short-term oscillator",
    },
    {
        "key": "nifty_stoch_d",
        "label": "NIFTY Stochastic %D",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — smoothed stochastic",
    },
    {
        "key": "nifty_williams_r",
        "label": "NIFTY Williams %R",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — overbought/oversold oscillator",
    },
    {
        "key": "nifty_cci_20",
        "label": "NIFTY CCI(20)",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — commodity channel index",
    },
    {
        "key": "nifty_adx_14",
        "label": "NIFTY ADX(14)",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — trend strength",
    },
    {
        "key": "nifty_atr_pct",
        "label": "NIFTY ATR %",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — normalized true range / volatility",
    },
    {
        "key": "nifty_golden_cross_signal",
        "label": "Golden cross signal",
        "category": "technical",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Macro Ridge input — 50/200 MA cross regime flag",
    },
    {
        "key": "constituent_momentum_7d",
        "label": "Constituent momentum (7d)",
        "category": "bottom_up",
        "source": "OpenAlgo INDstocks · yfinance (weighted 7d returns)",
        "role": "Bottom-up blend + macro — weighted index momentum",
    },
    {
        "key": "days_to_monthly_expiry",
        "label": "Days to monthly expiry",
        "category": "calendar",
        "source": "Indian F&O calendar",
        "role": "Macro Ridge + scenarios — expiry-week effects",
    },
    {
        "key": "is_budget_week",
        "label": "Union Budget week",
        "category": "calendar",
        "source": "Calendar flag",
        "role": "Macro Ridge + scenarios — Feb budget event risk",
    },
    {
        "key": "is_results_season",
        "label": "Earnings season",
        "category": "calendar",
        "source": "Calendar flag",
        "role": "Macro Ridge — peak results months",
    },
    {
        "key": "sector_breadth_mean_sentiment",
        "label": "Sector breadth sentiment",
        "category": "constituent_aggregate",
        "source": "Daily factor snapshot",
        "role": "Snapshot aggregate — cross-sector sentiment",
    },
    {
        "key": "earnings_events_14d_count",
        "label": "Earnings events (14d)",
        "category": "constituent_aggregate",
        "source": "Constituent calendars",
        "role": "Snapshot aggregate — near-term results density",
    },
    {
        "key": "alpha_zoo_ls_spread",
        "label": "Alpha Zoo L/S spread",
        "category": "alpha_zoo",
        "source": "vibetrading Alpha Zoo (alpha101 + qlib158 on Nifty 50)",
        "role": "Macro Ridge (promoted) — top-minus-bottom quintile consensus tilt",
    },
    {
        "key": "alpha_zoo_breadth",
        "label": "Alpha Zoo breadth",
        "category": "alpha_zoo",
        "source": "vibetrading Alpha Zoo consensus",
        "role": "Macro Ridge (promoted) — fraction of Nifty 50 with positive consensus",
    },
    {
        "key": "alpha_zoo_momentum_consensus",
        "label": "Alpha Zoo momentum consensus",
        "category": "alpha_zoo",
        "source": "vibetrading Alpha Zoo consensus",
        "role": "Macro Ridge (promoted) — cross-sectional mean consensus z-score",
    },
    {
        "key": "alpha_zoo_dispersion",
        "label": "Alpha Zoo dispersion",
        "category": "alpha_zoo",
        "source": "vibetrading Alpha Zoo consensus",
        "role": "Macro Ridge (promoted) — cross-sectional std of consensus",
    },
)

BOTTOM_UP_SIGNALS: tuple[dict[str, Any], ...] = (
    {
        "key": "constituent_sentiment",
        "label": "Per-stock FinBERT sentiment",
        "category": "bottom_up",
        "source": "company_research hub",
        "role": "70% weight in bottom-up expected return when momentum absent",
    },
    {
        "key": "constituent_momentum_7d_per_stock",
        "label": "Per-stock 7d return",
        "category": "bottom_up",
        "source": "yfinance",
        "role": "30% weight in bottom-up blend when available",
    },
    {
        "key": "constituent_weight",
        "label": "NIFTY 50 index weight",
        "category": "bottom_up",
        "source": "NSE / yfinance mcap",
        "role": "Scales each constituent contribution to index",
    },
    {
        "key": "earnings_bump",
        "label": "Earnings within horizon",
        "category": "bottom_up",
        "source": "Constituent event calendar",
        "role": "+0.5% bump when results fall inside horizon",
    },
    {
        "key": "sector_macro_link",
        "label": "Sector → macro sensitivity",
        "category": "bottom_up",
        "source": "constituent_factors sector map",
        "role": "Links each stock to oil, USD/INR, repo, FII drivers in attribution UI",
    },
    {
        "key": "constituent_news_headline",
        "label": "Per-stock news headline",
        "category": "bottom_up",
        "source": "company_research news stage",
        "role": "Top headlines surfaced in constituent_signals.factors",
    },
)

CONSTITUENT_RESEARCH_STAGES: tuple[dict[str, Any], ...] = (
    {
        "key": "company_research_batch",
        "label": "NIFTY 50 × company_research",
        "category": "constituent_research",
        "source": "batch_constituents.py",
        "role": "Runs full per-stock pipeline for all index members (cached hub, max_workers=4)",
    },
    {
        "key": "identity_in",
        "label": "Constituent identity & last price",
        "category": "constituent_research",
        "source": "OpenAlgo · yfinance · dalal BSE · nselib · Tapetide (optional)",
        "role": "Sector, industry, LTP — feeds weighting and sector breadth",
    },
    {
        "key": "peers_in",
        "label": "Peer set",
        "category": "constituent_research",
        "source": "screener.in · Tapetide (optional) · nselib · yfinance",
        "role": "Peer context for news fetch and relative sentiment",
    },
    {
        "key": "calendar_in",
        "label": "Corporate calendar",
        "category": "constituent_research",
        "source": "BSE · yfinance earnings · nselib · dalal BSE · Tapetide (if empty)",
        "role": "Results, AGM, ex-div — drives earnings_bump and scenario table",
    },
    {
        "key": "fundamentals_in",
        "label": "Fundamentals",
        "category": "constituent_research",
        "source": "dalal BSE · yfinance · nselib · Tapetide (optional)",
        "role": "P/E, margins, debt — context for attribution (not Ridge feature today)",
    },
    {
        "key": "filings_in",
        "label": "Regulatory filings",
        "category": "constituent_research",
        "source": "BSE filings API",
        "role": "Recent exchange disclosures per constituent",
    },
    {
        "key": "news_per_constituent",
        "label": "Company & peer news",
        "category": "constituent_research",
        "source": "news_aggregator (SearXNG · yfinance · Alpha Vantage · RSS)",
        "role": "Headlines ingested per stock; rolled into index_sentiment mean",
    },
    {
        "key": "sentiment_per_constituent",
        "label": "Headline sentiment score",
        "category": "constituent_research",
        "source": "SentimentPulse / FinBERT (SENTIMENT_PULSE_*)",
        "role": "Per-stock score → bottom-up blend and index_sentiment macro factor",
    },
    {
        "key": "macro_in_per_stock",
        "label": "India market context (per run)",
        "category": "constituent_research",
        "source": "OpenAlgo INDstocks · nselib · yfinance",
        "role": "India VIX + NIFTY level during company_research (shared with index macro)",
    },
)

CONSTITUENT_MARKET_DATA: tuple[dict[str, Any], ...] = (
    {
        "key": "constituent_india_ohlcv",
        "label": "Constituent OHLCV (7d)",
        "category": "constituent_market_data",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "7-day returns for per-stock and weighted index momentum",
    },
    {
        "key": "openalgo_constituent_quotes",
        "label": "Live constituent quotes",
        "category": "constituent_market_data",
        "source": "OpenAlgo INDstocks · OpenAlgo (OPENALGO_*)",
        "role": "LTP in identity stage; index spot via NIFTY quote",
    },
    {
        "key": "nifty50_weights",
        "label": "Index weights",
        "category": "constituent_market_data",
        "source": "NSE factsheet · cached weights · yfinance mcap fallback",
        "role": "Scales each constituent signal to index points",
    },
    {
        "key": "nifty_history",
        "label": "NIFTY index history",
        "category": "constituent_market_data",
        "source": "OpenAlgo INDstocks · yfinance",
        "role": "Technical features, 20d trend, regime, model backfill",
    },
)

NEWS_AND_SENTIMENT_MODULES: tuple[dict[str, Any], ...] = (
    {
        "key": "news_aggregator",
        "label": "Multi-source news aggregator",
        "category": "news_and_sentiment",
        "source": "SearXNG · yfinance · Alpha Vantage · RSS (SEARXNG_BASE_URL)",
        "role": "Parallel fetch + dedupe for company_research news stage",
    },
    {
        "key": "sentiment_pulse",
        "label": "SentimentPulse / FinBERT",
        "category": "news_and_sentiment",
        "source": "SENTIMENT_PULSE_MODE · SENTIMENT_PULSE_URL · SENTIMENT_PULSE_MODEL",
        "role": "In-process FinBERT or HTTP service; keyword heuristic fallback",
    },
    {
        "key": "material_news_watcher",
        "label": "Material headline watcher",
        "category": "news_and_sentiment",
        "source": "monitor/news_watcher.py",
        "role": "Keywords (earnings, RBI, FII, VIX…) trigger index/options refresh",
    },
    {
        "key": "index_sentiment_aggregate",
        "label": "Batch sentiment → index_sentiment",
        "category": "news_and_sentiment",
        "source": "macro_global.fetch_global_macro_snapshot",
        "role": "Mean FinBERT score across constituents enters Ridge model",
    },
)

DERIVATIVES_DATA: tuple[dict[str, Any], ...] = (
    {
        "key": "openalgo_nifty_chain",
        "label": "NIFTY option chain",
        "category": "derivatives",
        "source": "OpenAlgo MCP / REST",
        "role": "Live CE/PE OI and LTP — PCR and spot for index pipeline",
    },
    {
        "key": "nifty_total_call_oi",
        "label": "Total call OI",
        "category": "derivatives",
        "source": "OpenAlgo chain snapshot",
        "role": "Component of PCR; positioning context in macro snapshot",
    },
    {
        "key": "nifty_total_put_oi",
        "label": "Total put OI",
        "category": "derivatives",
        "source": "OpenAlgo chain snapshot",
        "role": "Component of PCR; positioning context in macro snapshot",
    },
    {
        "key": "qfinindia_expected_move",
        "label": "Expected move (ATM vol)",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Adjacent — used in options_research for NIFTY; not in index Ridge today",
    },
    {
        "key": "qfinindia_skew",
        "label": "Volatility skew",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Adjacent — put/call skew from chain analytics",
    },
    {
        "key": "qfinindia_tail_risk",
        "label": "Tail risk metric",
        "category": "derivatives",
        "source": "qfinindia (options_research)",
        "role": "Adjacent — OTM wing risk from chain analytics",
    },
)

PIPELINE_MODULES: tuple[dict[str, Any], ...] = (
    {
        "key": "index_research_aggregator",
        "label": "Index research orchestrator",
        "category": "pipeline",
        "source": "index_research/aggregator.py",
        "role": "Full pipeline: constituents → macro → predict → scenarios → ledger",
    },
    {
        "key": "light_refresh",
        "label": "Light refresh (macro drift)",
        "category": "pipeline",
        "source": "index_research/light_refresh.py",
        "role": "Re-runs macro + cached constituents when spot/macro moves (INDEX_MONITOR_*)",
    },
    {
        "key": "factor_store",
        "label": "Daily factor snapshots",
        "category": "pipeline",
        "source": "index_research/factor_store.py",
        "role": "Persists macro rows for backfill and walk-forward training",
    },
    {
        "key": "factor_backfill",
        "label": "Historical factor backfill",
        "category": "pipeline",
        "source": "index_research/factor_backfill.py",
        "role": "Rebuilds technical + calendar columns on NIFTY history",
    },
    {
        "key": "prediction_ledger",
        "label": "Prediction ledger & accuracy",
        "category": "pipeline",
        "source": "index_research/prediction_ledger.py",
        "role": "Stores forecasts; MAE and direction hit rate in accuracy block",
    },
    {
        "key": "backtest_runner",
        "label": "Factor backtest / audit",
        "category": "pipeline",
        "source": "index_research/backtest_runner.py",
        "role": "Walk-forward factor audit separate from live hub artifact",
    },
    {
        "key": "factor_explanation",
        "label": "Factor attribution & sensitivity",
        "category": "pipeline",
        "source": "index_research/explain.py",
        "role": "SHAP-like contributors, marginal sensitivity, event-impact curves",
    },
    {
        "key": "regime_classifier",
        "label": "Volatility regime",
        "category": "pipeline",
        "source": "index_research/regime.py",
        "role": "India VIX + 20d NIFTY trend → risk-on/off label",
    },
    {
        "key": "index_research_scheduler",
        "label": "Scheduled full / snapshot runs",
        "category": "pipeline",
        "source": "INDEX_RESEARCH_ENABLE_SCHEDULER · INDEX_RESEARCH_*_CRON",
        "role": "Daily macro snapshot + weekly full constituent refresh",
    },
    {
        "key": "index_monitor_scheduler",
        "label": "Intraday index monitor",
        "category": "pipeline",
        "source": "INDEX_MONITOR_ENABLE_SCHEDULER · INDEX_MONITOR_POLL_CRON",
        "role": "Polls macro drift + material news; triggers light_refresh",
    },
    {
        "key": "tapetide",
        "label": "Tapetide MCP (optional enrichment)",
        "category": "pipeline",
        "source": "TAPETIDE_TOKEN · TAPETIDE_MCP_URL · TAPETIDE_CACHE_MINUTES",
        "role": "Optional enrichment for single-stock research; skipped in Nifty 50 batch",
    },
    {
        "key": "screener_in",
        "label": "Screener.in peers (screenercli)",
        "category": "pipeline",
        "source": "screenercli (pip · research extra)",
        "role": "Primary peer-comparison source replacing Tapetide peer lists",
    },
    {
        "key": "ed_alpha",
        "label": "ED-ALPHA corp events",
        "category": "pipeline",
        "source": "ED_ALPHA_BASE_URL",
        "role": "US equities only (corp_events stage) — not used for NIFTY index members",
    },
    {
        "key": "nselib_flows",
        "label": "nselib capital market",
        "category": "pipeline",
        "source": "nselib (pip)",
        "role": "FII net 5d, India VIX — India macro ingest",
    },
    {
        "key": "rbi_cpi",
        "label": "RBI CPI / repo context",
        "category": "pipeline",
        "source": "index_research/sources/rbi_cpi.py",
        "role": "Inflation proxy and repo rate for macro snapshot + scenarios",
    },
)

MODEL_OUTPUTS: tuple[dict[str, Any], ...] = (
    {
        "key": "hybrid_ridge",
        "label": "Hybrid Ridge macro delta",
        "category": "model",
        "source": "Polynomial Ridge on macro factors",
        "role": "Macro overlay on bottom-up return",
    },
    {
        "key": "direction_classifier",
        "label": "Direction classifier",
        "category": "model",
        "source": "Logistic regression on macro poly features",
        "role": "direction_view + direction_confidence",
    },
    {
        "key": "scenario_reconcile",
        "label": "Scenario reconciliation",
        "category": "model",
        "source": "Event scenario table",
        "role": "Pulls headline forecast toward scenario anchor when divergent",
    },
)


def list_factor_catalog() -> dict[str, Any]:
    """Return grouped factor catalog for UI and API."""
    from trade_integrations.dataflows.company_research.source_registry import (
        list_india_company_data_sources,
    )

    return {
        "macro_and_technical": list(NIFTY_FACTOR_CATALOG),
        "bottom_up": list(BOTTOM_UP_SIGNALS),
        "constituent_research": list(CONSTITUENT_RESEARCH_STAGES),
        "constituent_market_data": list(CONSTITUENT_MARKET_DATA),
        "news_and_sentiment": list(NEWS_AND_SENTIMENT_MODULES),
        "derivatives": list(DERIVATIVES_DATA),
        "pipeline_modules": list(PIPELINE_MODULES),
        "model_layers": list(MODEL_OUTPUTS),
        "india_data_sources": list_india_company_data_sources(),
        "total_macro_keys": len(NIFTY_FACTOR_CATALOG),
    }
