#!/usr/bin/env bash
# Build .env.skyvern from repo .env — MiniMax LLM brain, no manual Skyvern API key.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/.env.skyvern"
SRC="$ROOT/.env"

if [[ -f "$SRC" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$SRC"
  set +a
fi

MINIMAX_KEY="${MINIMAX_API_KEY:-${MINIMAX_CN_API_KEY:-}}"
MINIMAX_BASE="${MINIMAX_BASE_URL:-https://api.minimax.io/v1}"
MINIMAX_BASE="${MINIMAX_BASE%/}"
MINIMAX_MODEL="${NSE_BROWSER_AGENT_MODEL:-MiniMax-M3}"

if [[ -z "$MINIMAX_KEY" ]]; then
  echo "MINIMAX_API_KEY (or MINIMAX_CN_API_KEY) required in $SRC" >&2
  exit 1
fi

cat >"$OUT" <<EOF
# Generated by scripts/sync_skyvern_env.sh — do not hand-edit; re-run script after .env changes.
ENV=local

# MiniMax as Skyvern agent brain (OpenAI-compatible)
ENABLE_OPENAI=false
ENABLE_OPENAI_COMPATIBLE=true
LLM_KEY=OPENAI_COMPATIBLE
OPENAI_COMPATIBLE_MODEL_NAME=${MINIMAX_MODEL}
OPENAI_COMPATIBLE_API_KEY=${MINIMAX_KEY}
OPENAI_COMPATIBLE_API_BASE=${MINIMAX_BASE}
OPENAI_COMPATIBLE_SUPPORTS_VISION=true

BROWSER_TYPE=chromium-headful
BROWSER_STREAMING_MODE=cdp
BROWSER_ADDITIONAL_ARGS=["--ignore-certificate-errors"]
MAX_STEPS_PER_RUN=50
LOG_LEVEL=INFO

# CORS for UI (:8080) → API (:8010) when ports differ from upstream defaults
ALLOWED_ORIGINS=["http://localhost:8080","http://127.0.0.1:8080"]
ALLOWED_ORIGIN_REGEX=^https?://(localhost|127\.0\.0\.1)(:\d+)?$
EOF

echo "Wrote $OUT (MiniMax model=${MINIMAX_MODEL}, base=${MINIMAX_BASE})"
