"""Defaults for autonomous agent instances."""

from __future__ import annotations

DEFAULT_WATCH_INTERVAL_MIN = 7
DEFAULT_RESEARCH_INTERVAL_MIN = 90
DEFAULT_BUDGET_INR = 20_000.0
DEFAULT_MAX_DAILY_LOSS_INR = 2_000.0
DEFAULT_CONFIDENCE_THRESHOLD = 75
DEFAULT_MODE = "paper"
MAX_CONCURRENT_AGENTS = 10
PROPOSAL_TTL_MS = 30 * 60 * 1000
DEFAULT_MIN_HOLD_MINUTES = 10
DEFAULT_MIN_STRATEGY_SCORE = 0.45

REQUIRED_PROPOSAL_FIELDS = ("symbols",)
